# Generated by Django 5.0.6 on 2024-05-24 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_hospital_remove_service_doctor_service_doctor_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
